### PR TITLE
Improve Indonesian translation

### PR DESCRIPTION
**Pull request by tyok**
Hi,

I want to add a couple improvements for Indonesian translation:
- Change 'Nopember' to 'November' ([it's the correct spelling](https://id.wikipedia.org/wiki/November)).
- Update time format to use dots as separator.
- Add tests.

### CODE REVIEW

**Comment by AlexWayfer** [comment]
Hi!

Thank you for your contribution.

**Comment by tyok** [comment]
I fixed them, but interrestingly the code causing the errors have been there since dca5ba4d. Not sure why previous checks in other pull requests have been green.

Also, my fix should also make #220 green.

**Comment by AlexWayfer** [comment]
Sorry, there is some magic…

I couldn't reproduce the fails locally, and just re-run jobs for #220, and everything is OK.

Please, delete the last your commit and, I guess, we'll have green CI.

**Comment by tyok** [comment]
I removed [my last commit](https://github.com/tyok/r18n/commit/9e412d9eb86cda3384d797065edf24387ad80e65), and it's red again. Tried to rerun the CI a couple times too.

Any idea on this?

**Comment by AlexWayfer** [comment]
> Any idea on this?

Sorry, rebase on actual master please.

You know, like…

```
git checkout master
git fetch upstream
git rebase upstream/master
git push
git checkout your_branch
git rebase master
git push -f
```

**Comment by tyok** [comment]
It's already up to date with upstream master now: https://github.com/tyok/r18n/compare/improve-indonesian...r18n:master. But the tests are still failing.

Sorry for the trouble, I'll try to compare the test runs and see if I can find anything. For now, I still think https://github.com/tyok/r18n/commit/9e412d9eb86cda3384d797065edf24387ad80e65 is the solution, since the `raise_error` matcher should run fine with block expectation.

**Comment by AlexWayfer** [comment]
I found the problem (the root of magic):

There are disputes about implicit and explicit blocks for `expect`:

1. https://github.com/rspec/rspec-expectations/issues/526
2.https://github.com/rspec/rspec-expectations/pull/530
3. https://github.com/rspec/rspec-expectations/issues/536
4. https://github.com/rubocop-hq/rspec-style-guide/issues/76
5. https://github.com/rubocop-hq/rubocop-rspec/pull/789
6. https://github.com/rspec/rspec-expectations/pull/1125
7. https://github.com/rspec/rspec-expectations/pull/1066

and, finally: https://github.com/rodjek/rspec-puppet/pull/767

So, with `gem 'rspec-expectations', '3.8.4'` there are no errors.

With `3.8.5` there are errors.

And with `3.8.6` there are no errors again.

I think, some build on Cirrus CI was with `3.8.5`, and was cached. And without Gemfile or Ruby changes it's still alive.

I'll try to fix it in `master`.

**Comment by AlexWayfer** [comment]
#221 with fix is merged, so, please, rebase and we're ready to merge it, I think.

**Comment by tyok** [comment]
Sorry for the late response. I didn't expect the problem to be rspec, and only a very specific version of it. Great sleuthing skills, @AlexWayfer!

Also, I've rebased my commit as needed. Thanks for your time again.

**Comment by AlexWayfer** [comment]
Thank you for your contribution!

**Pull request merged**
